/*Listar base de datos del servidor*/
SHOW DATABASES;

/*CREAR BASE DE DATOS*/
CREATE DATABASE dbMinimarket;

/*PONER EN USO LA BASE DE DATOS*/
USE dbMinimarket;

/*Crear tabla*/
CREATE TABLE VENDEDOR (
    CODVEND CHAR(6),
    NOMVEND VARCHAR(50),
    APEVEND VARCHAR(80),
    DOCVEND VARCHAR(10),
    CELVEND CHAR(9),
    DOMVEND VARCHAR(80),
    PRIMARY KEY (CODVEND)
);
